# Generated by Django 2.2.16 on 2020-09-30 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('respa_outlook', '0003_respaoutlookreservation_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respaoutlookconfiguration',
            name='resource',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_Resources', to='resources.Resource', verbose_name='Resource'),
        ),
    ]
