# Generated by Django 2.2.16 on 2020-09-30 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0122_auto_20200917_1300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessibilityvalue',
            options={'ordering': ('order',), 'verbose_name': 'saavutettavuusarvo', 'verbose_name_plural': 'accessibility values'},
        ),
        migrations.AlterModelOptions(
            name='accessibilityviewpoint',
            options={'ordering': ('order_text',), 'verbose_name': 'saavutettavuusnäkökulma', 'verbose_name_plural': 'accessibility viewpoints'},
        ),
        migrations.AlterModelOptions(
            name='resourceaccessibility',
            options={'ordering': ('id',), 'verbose_name': 'resurssin saavutettavuuden yhteenveto', 'verbose_name_plural': 'resurssin saavutettavuuden yhteenvedot'},
        ),
        migrations.AlterModelOptions(
            name='unitaccessibility',
            options={'ordering': ('id',), 'verbose_name': 'toimipisteen saavutettavuuden yhteenveto', 'verbose_name_plural': 'toimipisteen saavutettavuuden yhteenvedot'},
        ),
        migrations.AlterField(
            model_name='accessibilityvalue',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Järjestysprioriteetti'),
        ),
        migrations.AlterField(
            model_name='accessibilityvalue',
            name='value',
            field=models.CharField(max_length=128, unique=True, verbose_name='Saavutettavuusyhteenvedon arvo'),
        ),
        migrations.AlterField(
            model_name='cleanresourceid',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources_cleanresourceid_tagged_items', to='contenttypes.ContentType', verbose_name='content type'),
        ),
        migrations.AlterField(
            model_name='resourceaccessibility',
            name='order',
            field=models.IntegerField(verbose_name='Resurssin järjestysprioriteetti'),
        ),
        migrations.AlterField(
            model_name='resourceaccessibility',
            name='value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.AccessibilityValue', verbose_name='Saavutettavuusyhteenvedon arvo'),
        ),
        migrations.AlterField(
            model_name='resourceaccessibility',
            name='viewpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_accessibility_summaries', to='resources.AccessibilityViewpoint', verbose_name='Resurssin saavutettavuus'),
        ),
        migrations.AlterField(
            model_name='unitaccessibility',
            name='order',
            field=models.IntegerField(verbose_name='Resurssin järjestysprioriteetti'),
        ),
        migrations.AlterField(
            model_name='unitaccessibility',
            name='value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.AccessibilityValue', verbose_name='Saavutettavuusyhteenvedon arvo'),
        ),
        migrations.AlterField(
            model_name='unitaccessibility',
            name='viewpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_accessibility_summaries', to='resources.AccessibilityViewpoint', verbose_name='Resurssin saavutettavuus'),
        ),
    ]
